extends Control

# --- LEFT PANEL REFERENCES ---
@onready var name_label = $MainContainer/LeftPanelBackground/LeftPanel/TextAndPortrait/Header/NameLabel
@onready var class_label = $MainContainer/LeftPanelBackground/LeftPanel/TextAndPortrait/Header/ClassLabel
@onready var backstory_label = $MainContainer/LeftPanelBackground/LeftPanel/TextAndPortrait/Header/Description
@onready var portrait_rect = $MainContainer/LeftPanelBackground/LeftPanel/TextAndPortrait/Portrait

# --- ABILITY REFERENCES ---
@onready var ability1_label = $MainContainer/LeftPanelBackground/LeftPanel/AbilityContainer/Ability1/Description
@onready var ability2_container = $MainContainer/LeftPanelBackground/LeftPanel/AbilityContainer/Ability2
@onready var ability2_label = $MainContainer/LeftPanelBackground/LeftPanel/AbilityContainer/Ability2/Description

# --- RIGHT PANEL REFERENCES ---
@onready var stat_hexagon = $"MainContainer/RightPanelBackground/RightPanel/StatHexagon"
@onready var item_icon_1 = $"MainContainer/RightPanelBackground/RightPanel/ItemContainer/Slot1"
@onready var item_icon_2 = $"MainContainer/RightPanelBackground/RightPanel/ItemContainer/Slot2"

# --- DATA ---
var current_index: int = 0
var all_units: Array = []

func _ready():
	visible = false

# --- MAIN ACTIONS ---
func open():
	if RunManager:
		all_units = RunManager.owned_units
	
	if all_units.is_empty():
		return

	# Logic only: No Z-Index modification here
	current_index = 0
	_update_display()
	visible = true

func close():
	visible = false

# --- INTERACTION ---
# Inside UnitDetailView.gd

func show_specific_unit(target_unit_data: UnitData):
	# REFRESH DATA to ensure we find the unit
	if RunManager:
		all_units = RunManager.owned_units
		
	var index = all_units.find(target_unit_data)
	if index != -1:
		current_index = index
		_update_display()
		visible = true
	else:
		print("DEBUG: Clicked unit not found in RunManager list!")

# --- VISUAL UPDATE LOGIC ---
func _update_display():
	if all_units.is_empty(): return
	
	# Bounds Check
	if current_index < 0: current_index = 0
	if current_index >= all_units.size(): current_index = 0
	
	var unit = all_units[current_index]
	
	# 1. Update Text (with safety checks)
	if name_label: name_label.text = unit.character_name
	if class_label: class_label.text = unit.unit_class
	if backstory_label: backstory_label.text = unit.backstory
	
	# 2. Portrait with Fallback
	if portrait_rect:
		if unit.portrait:
			portrait_rect.texture = unit.portrait
		elif unit.icon:
			portrait_rect.texture = unit.icon
		else:
			portrait_rect.texture = null
			
	# 3. Abilities
	if ability1_label: ability1_label.text = unit.ability1_text
		
	if ability2_container:
		if unit.ability2_text == "":
			ability2_container.visible = false
		else:
			ability2_container.visible = true
			if ability2_label: ability2_label.text = unit.ability2_text

	# 4. Stats
	if stat_hexagon:
		stat_hexagon.update_stats(unit.get_total_stats(), [])
	
	# 5. Items
	if item_icon_1: _update_item_slot(item_icon_1, unit.equipped_items[0])
	if item_icon_2: _update_item_slot(item_icon_2, unit.equipped_items[1])

func _update_item_slot(icon_rect: TextureRect, item: ItemData):
	if icon_rect == null: return
	
	if item != null:
		# Has Item: Show Icon normally
		icon_rect.texture = item.icon
		icon_rect.modulate = Color(1, 1, 1, 1) # Full White (Normal Colors)
		icon_rect.tooltip_text = item.item_name + "\n" + item.description
	else:
		# Empty Slot: Show Black Rectangle
		
		# 1. Create a 1x1 pixel texture generated by code
		var placeholder = PlaceholderTexture2D.new()
		placeholder.size = Vector2(1, 1) # Minimal size, it will stretch
		
		icon_rect.texture = placeholder
		icon_rect.modulate = Color(0, 0, 0, 1) # Turn the white pixel BLACK
		icon_rect.tooltip_text = "Empty Slot"
